- include_vars: group_vars/postgres.yaml
- include_vars: group_vars/mongo.yaml
- include_vars: group_vars/mysql.yaml
- include_vars: host_vars/{{ inventory_hostname }}.yaml

- import_tasks: preparation.yaml
  tags:
  - prepare
  - install

- import_tasks: install_teleport.yaml
  tags:
  - install
  - update

- import_tasks: configure_main_server.yaml
  tags:
  - install
  - configure-teleport-server
  when: "'teleport-server' in group_names"

- import_tasks: configure_mongo_server.yaml
  tags:
  - update-mongodb-certs
  when: "'mongo' in group_names"

- import_tasks: configure_mysql_server.yaml
  when: "'mysql' in group_names"
  tags:
  - update-mysql-certs

- import_tasks: configure_postgresql_server.yaml
  when: "'postgres' in group_names"
  tags:
  - update-psql-certs

- import_tasks: configure_postgresql_users.yaml
  when: "'postgres' in group_names"
  tags:
  - postgresql-users

- import_tasks: configure_node_server.yaml
  when: "'mysql' not in group_names and 'postgres' not in group_names and 'teleport-server' not in group_names and 'mongo' not in group_names"
  tags:
  - register_node
