---
- name: Prepare - Create teleport certificates directory
  file:
    path: "{{ teleport_server_cert_dir }}"
    state: directory
  when: "'teleport-server' in group_names"

- name: Prepare - Create Teleport token directory
  file:
    path: "{{ teleport_token_path }}"
    state: directory
    mode: 0755

- name: Prepare - Create Teleport logs directory
  file:
    path: "{{ teleport_logs_path }}"
    state: directory
    mode: 0755